apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml
images:
- name: docker.io/fluxcd/flux
  newName: acraks3sihgykmts3uk.azurecr.io/fluxcd/flux
- name: docker.io/library/memcached
  newName: acraks3sihgykmts3uk.azurecr.io/library/memcached